FROM nexus-preprod.chubbdigital.com:9006/chubb-rhe17-jre8:v7.9-2021q1-j8u281
USER root
WORKDIR /users/home
EXPOSE 8080
RUN curl -LJO http://localhost:8081/repository/pipeline_snapshot_test1/docker/jar/sample_app/spring_boot/0.0.1/spring-boot-0.0.1.jar
USER appUser
CMD ["sh", "-c", "java -jar spring-boot-0.0.1.jar"]