apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    env: test
    owner: raja
    appName: skaffold-kaniko
spec:
   ports:
   - name: demoapp1
     port: 80
     protocol: TCP
     targetPort: 8080
   selector:
     appName: skaffold-kaniko
   #type: LoadBalance